using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;

namespace AnvilMap.Generator;

// Turns the resolved MappingModel list into GeneratedMappings.g.cs. Split by responsibility:
//   - MappingEmitter.Imperative.cs  - the To{Dest}() extension methods.
//   - MappingEmitter.Projection.cs  - the ProjectTo{Dest}() IQueryable extension methods.
//   - MappingEmitter.Dispatcher.cs  - the runtime dispatcher and IMapper service.
// AM006 (below) is the one whole-mapping rejection, checked here since it needs three fields
// together (DestinationIsInitOnly, DestinationHasParameterlessConstructor,
// ConstructorParameterProperties).
internal static partial class MappingEmitter
{
    public static string Emit(
        IReadOnlyCollection<MappingModel> mappings,
        ConsumerCapabilities capabilities,
        IReadOnlyCollection<InterceptedMapCall> interceptedCalls,
        Action<Diagnostic>? report = null)
    {
        var validMappings = new List<MappingModel>();

        foreach (var mapping in mappings)
        {
            // Init-only property + no parameterless constructor + no matched constructor
            // (see MappingResolver.TryMatchConstructor) can't be built at all - skipped rather
            // than emitting code that won't compile.
            if (HasInitOnlyProperty(mapping) &&
                !mapping.DestinationHasParameterlessConstructor &&
                mapping.ConstructorParameterProperties is null)
            {
                report?.Invoke(Diagnostic.Create(
                    Diagnostics.NoParameterlessConstructor,
                    Location.None,
                    mapping.Source.DisplayName,
                    mapping.Destination.DisplayName));
                continue;
            }

            validMappings.Add(mapping);
        }

        // Keyed lookup for MappingEmitter.Projection.cs to inline a nested/element type's own
        // projection expression instead of calling a method (SQL projections can't call methods).
        var byPair = validMappings.ToDictionary(m => (m.Source.FullyQualifiedName, m.Destination.FullyQualifiedName));

        // A Nested/Enumerable property's mapping only had to be *declared* (not resolved and
        // emitted) to reach that Kind in MappingResolver - if the referenced mapping was later
        // dropped from validMappings above (e.g. AM006), this property's generated code has
        // nothing to call. Reported here (AM018) rather than left to surface as a confusing
        // compiler error; the returned set lets EmitProjection below tell that case apart from an
        // actual cycle instead of misreporting it as AM002.
        var mappingsWithOrphanedNestedReference = ReportOrphanedNestedMappings(validMappings, byPair, report);

        ReportIneffectiveMaxDepth(validMappings, report);

        // ToImmutableArray() lives on System.Collections.Immutable.ImmutableArray, an extension
        // method - only added when at least one mapping actually uses the shape, so consumers
        // who never touch ImmutableArray<T> don't get an unused using.
        var usesImmutableArray = validMappings.Any(m => m.Properties.Any(p =>
            p.Kind == PropertyMappingKind.Enumerable && p.DestinationCollectionShape == CollectionShape.ImmutableArray));

        var writer = new CodeWriter();

        writer.WriteLine("// <auto-generated />");
        if (capabilities.UseNullableReferenceTypes)
        {
            writer.WriteLine("#nullable enable");
        }

        writer.WriteLine();
        writer.WriteLine("using System;");
        if (capabilities.CanUseFrozenDictionary)
        {
            writer.WriteLine("using System.Collections.Frozen;");
        }

        writer.WriteLine("using System.Collections.Generic;");
        if (usesImmutableArray)
        {
            writer.WriteLine("using System.Collections.Immutable;");
        }

        writer.WriteLine("using System.Linq;");
        writer.WriteLine("using System.Linq.Expressions;");
        writer.WriteLine();

        bool emittedInterceptors;

        // File-scoped namespace (`namespace X;`) needs C# 10 - always emit the braced form.
        using (writer.Block("namespace AnvilMap"))
        {
            using (writer.Block("public static class GeneratedMappings"))
            {
                foreach (var mapping in validMappings)
                {
                    EmitMapping(writer, mapping, capabilities, report);
                }

                // Projection fields have no initializer (see MappingEmitter.Projection.cs) and are
                // assigned below in one explicit static constructor instead, since an implicit one
                // can't carry an attribute - needed for the
                // [DynamicDependency]/[UnconditionalSuppressMessage] pair further down.
                var projectionFieldInitializers = new List<string>();

                // Destinations whose projection actually emits a trailing `{ Prop = value }` block
                // (not a pure Expression.New(ctor, args), e.g. a fully constructor-covered record)
                // - only those need Expression.Bind trim protection.
                var destinationTypesUsingBind = new HashSet<string>();

                foreach (var mapping in validMappings)
                {
                    EmitProjection(writer, mapping, byPair, mappingsWithOrphanedNestedReference, projectionFieldInitializers, destinationTypesUsingBind, report);
                }

                if (projectionFieldInitializers.Count > 0)
                {
                    // The C# compiler compiles a `new Dest { Prop = value }` object-initializer
                    // inside an Expression<Func<...>> via Expression.Bind(MethodInfo, Expression),
                    // which is [RequiresUnreferencedCode] and triggers IL2026 under trimming/AOT -
                    // not something particular to this generator. Only attempted when the
                    // consumer's compilation has these types (net6+, see
                    // ConsumerCapabilities.CanSuppressTrimWarnings); older consumers can't run the
                    // trim/AOT analyzer anyway, so there's nothing to suppress.
                    if (capabilities.CanSuppressTrimWarnings && destinationTypesUsingBind.Count > 0)
                    {
                        // DynamicDependency is the actual guarantee (keeps the property regardless
                        // of other reachability); UnconditionalSuppressMessage only silences the
                        // warning - neither makes the other redundant.
                        foreach (var destinationType in destinationTypesUsingBind)
                        {
                            writer.WriteLine($"[System.Diagnostics.CodeAnalysis.DynamicDependency(System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicProperties, typeof({destinationType}))]");
                        }

                        writer.WriteLine("[System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"Trimming\", \"IL2026\", Justification = \"The [DynamicDependency] attributes above already guarantee every destination property Expression.Bind reflects over here is kept.\")]");
                    }

                    using (writer.Block("static GeneratedMappings()"))
                    {
                        foreach (var initializer in projectionFieldInitializers)
                        {
                            writer.WriteLine(initializer);
                        }
                    }

                    writer.WriteLine();
                }

                EmitGenericDispatcher(writer, validMappings, capabilities);
            }

            writer.WriteLine();

            EmitMapperService(writer, validMappings);

            // Still inside `namespace AnvilMap` - the interceptor class lives alongside
            // GeneratedMappings/AnvilMapService so InterceptorsNamespaces only ever needs to
            // list this one namespace, not a second one.
            emittedInterceptors = EmitInterceptors(writer, interceptedCalls, capabilities, byPair);
        }

        // The InterceptsLocation polyfill must be a top-level type in exactly
        // System.Runtime.CompilerServices (the compiler recognizes it by that name alone - the BCL
        // never exposes a public one, confirmed empirically), so it can't nest inside the namespace
        // block just closed above. Only emitted when an interceptor actually exists to attribute.
        if (emittedInterceptors)
        {
            EmitInterceptsLocationPolyfill(writer);
        }

        return writer.Build();
    }

    private static bool HasInitOnlyProperty(MappingModel mapping)
        => mapping.Properties.Any(p => p.DestinationIsInitOnly);

    private static bool HasNoTwoArgOverload(MappingModel mapping)
        => HasInitOnlyProperty(mapping) || mapping.Includes is { Count: > 0 };

    // Returns the (source, destination) key of every validMappings entry that has at least one
    // Nested/Enumerable property whose own referenced mapping isn't in byPair - used by
    // EmitProjection to tell that case apart from an actual cycle. A self-recursive property
    // (mapping.Source/Destination referencing the same mapping being iterated) never trips this:
    // byPair is built from validMappings itself, so the mapping's own pair is always present.
    private static HashSet<(string Source, string Destination)> ReportOrphanedNestedMappings(
        IReadOnlyCollection<MappingModel> validMappings,
        Dictionary<(string Source, string Destination), MappingModel> byPair,
        Action<Diagnostic>? report)
    {
        var affected = new HashSet<(string, string)>();

        foreach (var mapping in validMappings)
        {
            foreach (var property in mapping.Properties)
            {
                var (nestedSource, nestedDestination) = property.Kind switch
                {
                    PropertyMappingKind.Nested => (property.SourceType, property.DestinationType),
                    PropertyMappingKind.Enumerable => (property.ElementSourceType, property.ElementDestinationType),
                    _ => (null, null)
                };

                // Identical element types never call a nested mapping method at all, so there's
                // nothing here for byPair to find "orphaned" - skip, or a primitive/value
                // element type (e.g. int) always fails this lookup and fires a false AM018.
                if (nestedSource is null || nestedDestination is null ||
                    nestedSource.FullyQualifiedName == nestedDestination.FullyQualifiedName ||
                    byPair.ContainsKey((nestedSource.FullyQualifiedName, nestedDestination.FullyQualifiedName)))
                {
                    continue;
                }

                affected.Add((mapping.Source.FullyQualifiedName, mapping.Destination.FullyQualifiedName));

                report?.Invoke(Diagnostic.Create(
                    Diagnostics.NestedMappingSkipped,
                    Location.None,
                    property.DestinationPropertyName,
                    mapping.Source.DisplayName,
                    mapping.Destination.DisplayName,
                    nestedSource.DisplayName,
                    nestedDestination.DisplayName));
            }
        }

        return affected;
    }

    // MaxDepth's depth-guard is only threaded through the plain mutable-property shape - a
    // constructor-based, init-only, or polymorphic destination never gets a recursionContext,
    // regardless of MaxDepth. Reports AM020 for that mismatch, and for MaxDepth set on a mapping
    // with no actually self-recursive property - ignoring this warning on a genuine reference
    // cycle crashes with an uncatchable StackOverflowException, confirmed empirically.
    private static void ReportIneffectiveMaxDepth(IReadOnlyCollection<MappingModel> validMappings, Action<Diagnostic>? report)
    {
        foreach (var mapping in validMappings)
        {
            if (mapping.MaxDepth <= 0)
            {
                continue;
            }

            var supportsGuard = mapping.ConstructorParameterProperties is null &&
                !mapping.Properties.Any(p => p.DestinationIsInitOnly) &&
                mapping.Includes is not { Count: > 0 };

            string? reason = !supportsGuard
                ? "the destination isn't built via plain mutable-property assignment (it has init-only properties, is constructed through a matched constructor, or is a polymorphic [MapInclude] mapping), which the depth-guard mechanism doesn't support"
                : !mapping.Properties.Any(p => IsSelfRecursive(p, mapping))
                    ? "no property on this mapping is actually self-recursive (maps back to this same source/destination pair), so there's nothing to guard against"
                    : null;

            if (reason is not null)
            {
                report?.Invoke(Diagnostic.Create(
                    Diagnostics.MaxDepthHasNoEffect,
                    Location.None,
                    mapping.Source.DisplayName,
                    mapping.Destination.DisplayName,
                    reason));
            }
        }
    }

    // ObservableCollection isn't a suffix call at all (no BCL extension materializes into it) -
    // callers special-case it before ever reaching this.
    private static string MaterializeCall(CollectionShape shape)
        => shape switch
        {
            CollectionShape.Array => "ToArray()",
            CollectionShape.HashSet => "ToHashSet()",
            CollectionShape.ImmutableArray => "ToImmutableArray()",
            _ => "ToList()"
        };
}
