namespace GeneratedMapper.Generator;

// One discovered call site syntactically matching `GeneratedMappings.Map<TSource,TDestination>(...)`
// (see MappingSourceGenerator's call-site discovery stage). The method symbol itself can never be
// resolved here - GeneratedMappings is generated by this same generator in the same pass, so it
// doesn't exist yet in the compilation a syntax provider's SemanticModel sees. SourceTypeName/
// DestinationTypeName come from resolving just the two type-argument syntax nodes instead, which -
// unlike the method symbol - resolve fine since they're ordinary pre-existing consumer types.
internal readonly record struct InterceptedMapCall(
    string SourceTypeName,
    string DestinationTypeName,
    bool IsTwoArgOverload,
    int LocationVersion,
    string LocationData);
