using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace GeneratedMapper.Generator;

// Turns the resolved MappingModel list into GeneratedMappings.g.cs. Split by responsibility:
//   - MappingEmitter.Imperative.cs  - the To{Dest}() extension methods.
//   - MappingEmitter.Projection.cs  - the ProjectTo{Dest}() IQueryable extension methods.
//   - MappingEmitter.Dispatcher.cs  - the runtime dispatcher and IMapper service.
// GM006 (below) is the one whole-mapping rejection, checked here since it needs three fields
// together (DestinationIsInitOnly, DestinationHasParameterlessConstructor,
// ConstructorParameterProperties).
internal static partial class MappingEmitter
{
    public static string Emit(
        IReadOnlyCollection<MappingModel> mappings,
        ConsumerCapabilities capabilities,
        Action<Diagnostic>? report = null)
    {
        var validMappings = new List<MappingModel>();

        foreach (var mapping in mappings)
        {
            // Init-only property + no parameterless constructor + no matched constructor
            // (see MappingResolver.TryMatchConstructor) can't be built at all - skipped rather
            // than emitting code that won't compile.
            if (HasInitOnlyProperty(mapping) &&
                !mapping.DestinationHasParameterlessConstructor &&
                mapping.ConstructorParameterProperties is null)
            {
                report?.Invoke(Diagnostic.Create(
                    Diagnostics.NoParameterlessConstructor,
                    Location.None,
                    mapping.Source.DisplayName,
                    mapping.Destination.DisplayName));
                continue;
            }

            validMappings.Add(mapping);
        }

        // Keyed lookup for MappingEmitter.Projection.cs to inline a nested/element type's own
        // projection expression instead of calling a method (SQL projections can't call methods).
        var byPair = validMappings.ToDictionary(m => (m.Source.FullyQualifiedName, m.Destination.FullyQualifiedName));

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        if (capabilities.UseNullableReferenceTypes)
            sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        if (capabilities.CanUseFrozenDictionary)
            sb.AppendLine("using System.Collections.Frozen;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Linq.Expressions;");
        sb.AppendLine();
        // File-scoped namespace (`namespace X;`) needs C# 10 - always emit the braced form.
        sb.AppendLine("namespace GeneratedMapper");
        sb.AppendLine("{");
        sb.AppendLine("public static class GeneratedMappings");
        sb.AppendLine("{");

        foreach (var mapping in validMappings)
            EmitMapping(sb, mapping, capabilities, report);

        // Projection fields have no initializer (see MappingEmitter.Projection.cs) and are
        // assigned below in one explicit static constructor instead, since an implicit one can't
        // carry an attribute - needed for the [DynamicDependency]/[UnconditionalSuppressMessage]
        // pair further down.
        var projectionFieldInitializers = new List<string>();

        // Destinations whose projection actually emits a trailing `{ Prop = value }` block (not
        // a pure Expression.New(ctor, args), e.g. a fully constructor-covered record) - only
        // those need Expression.Bind trim protection.
        var destinationTypesUsingBind = new HashSet<string>();

        foreach (var mapping in validMappings)
            EmitProjection(sb, mapping, byPair, projectionFieldInitializers, destinationTypesUsingBind, report);

        if (projectionFieldInitializers.Count > 0)
        {
            // The C# compiler compiles a `new Dest { Prop = value }` object-initializer inside an
            // Expression<Func<...>> via Expression.Bind(MethodInfo, Expression), which is
            // [RequiresUnreferencedCode] and triggers IL2026 under trimming/AOT - not something
            // particular to this generator. Only attempted when the consumer's compilation has
            // these types (net6+, see ConsumerCapabilities.CanSuppressTrimWarnings); older
            // consumers can't run the trim/AOT analyzer anyway, so there's nothing to suppress.
            if (capabilities.CanSuppressTrimWarnings && destinationTypesUsingBind.Count > 0)
            {
                // DynamicDependency is the actual guarantee (keeps the property regardless of
                // other reachability); UnconditionalSuppressMessage only silences the warning -
                // neither makes the other redundant.
                foreach (var destinationType in destinationTypesUsingBind)
                    sb.AppendLine($"    [System.Diagnostics.CodeAnalysis.DynamicDependency(System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicProperties, typeof({destinationType}))]");

                sb.AppendLine("    [System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"Trimming\", \"IL2026\", Justification = \"The [DynamicDependency] attributes above already guarantee every destination property Expression.Bind reflects over here is kept.\")]");
            }

            sb.AppendLine("    static GeneratedMappings()");
            sb.AppendLine("    {");
            foreach (var initializer in projectionFieldInitializers)
                sb.AppendLine(initializer);
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        EmitGenericDispatcher(sb, validMappings, capabilities);

        sb.AppendLine("}");
        sb.AppendLine();

        EmitMapperService(sb, validMappings);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static bool HasInitOnlyProperty(MappingModel mapping)
        => mapping.Properties.Any(p => p.DestinationIsInitOnly);

    private static string MaterializeCall(CollectionShape shape)
        => shape switch
        {
            CollectionShape.Array => "ToArray()",
            CollectionShape.HashSet => "ToHashSet()",
            _ => "ToList()"
        };
}
