using System;
using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace GeneratedMapper.Generator;

/// <summary>
/// Incremental generator entry point: finds every <c>[MapTo]</c>- or <c>[MapFrom]</c>-decorated
/// type across the compilation, resolves each declared mapping's properties via <see cref="MappingResolver"/>
/// (nested/enumerable/converted/conditional matching, diagnostics for anything unmappable),
/// and emits the result as a single <c>GeneratedMappings.g.cs</c> file via
/// <see cref="MappingEmitter"/> - the imperative <c>To{Dest}()</c> extension methods, the
/// <c>ProjectTo{Dest}()</c> SQL-projection extensions, and the runtime dispatcher/
/// <c>IMapper</c> service.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class MappingSourceGenerator : IIncrementalGenerator
{
    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Stage 1 - discovery: ForAttributeWithMetadataName syntactically pre-filters before
        // binding symbols. Each match yields zero or more MappingDeclaration values (one per
        // [MapTo]/[MapFrom] - see MappingDiscovery), which SelectMany flattens. Two separate
        // pipelines - [MapTo] on the source type, [MapFrom] on the destination type - merged
        // into one declarations stream before Collect(); MappingDiscovery normalizes both into
        // the same MappingDeclaration shape, so nothing downstream needs to know which
        // attribute originally declared a given mapping.
        var mapToDeclarations = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                GeneratorConstants.MapToAttribute,
                predicate: static (node, _) => node is ClassDeclarationSyntax or StructDeclarationSyntax,
                transform: static (ctx, _) => MappingDiscovery.Discover(ctx))
            .SelectMany(static (declarations, _) => declarations);

        var mapFromDeclarations = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                GeneratorConstants.MapFromAttribute,
                predicate: static (node, _) => node is ClassDeclarationSyntax or StructDeclarationSyntax,
                transform: static (ctx, _) => MappingDiscovery.DiscoverFrom(ctx))
            .SelectMany(static (declarations, _) => declarations);

        var declarations = mapToDeclarations.Collect()
            .Combine(mapFromDeclarations.Collect())
            .Select(static (pair, _) =>
            {
                var (mapTo, mapFrom) = pair;
                return mapTo.AddRange(mapFrom);
            });

        // Call-site discovery for interceptor-based direct dispatch: finds syntactically-visible
        // `GeneratedMappings.Map<TSource,TDestination>(...)` invocations. Not attribute-based, so
        // CreateSyntaxProvider rather than ForAttributeWithMetadataName - and deliberately never
        // tries to bind the `Map` method symbol itself: GeneratedMappings is generated by this same
        // generator in this same pass, so it doesn't exist yet in the compilation a syntax
        // provider's SemanticModel sees (confirmed empirically - a same-pass-generated type's calls
        // never resolve via GetSymbolInfo here). The receiver is matched syntactically instead
        // (rightmost identifier is "GeneratedMappings"); only the two type arguments are resolved
        // semantically, which works regardless of whether the invoked method itself resolves.
        var interceptedCalls = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidateMapInvocation(node),
                transform: static (ctx, ct) => TryGetInterceptedMapCall(ctx, ct))
            .Where(static call => call is not null)
            .Select(static (call, _) => call!.Value)
            .Collect();

        // Collect() forces the whole pipeline to re-run whenever any mapped type changes -
        // accepted, not an oversight: resolving one mapping can depend on any other
        // (MappingResolver needs the full MappingGraph). Measured to stay well under 100ms
        // even at 1,000+ mapped types.
        var combined = context.CompilationProvider.Combine(declarations).Combine(interceptedCalls);

        context.RegisterSourceOutput(combined, static (spc, combinedPair) =>
        {
            var ((compilation, allDeclarations), interceptedCallSites) = combinedPair;

            if (allDeclarations.IsDefaultOrEmpty)
                return;

            // Stage 2 - graph construction: every declaration (plus its reverse, if declared)
            // goes into one MappingGraph before resolution starts.
            var graph = new MappingGraph();
            foreach (var declaration in allDeclarations)
                graph.Add(declaration, spc.ReportDiagnostic);

            // [MapIgnore] correctness checks that need every declaration targeting a given
            // destination at once (a stale/typo'd source type, or a redundant combination) -
            // run once per destination here, rather than once per declaration inside
            // MappingResolver.Resolve, which would report the same finding multiple times.
            MapIgnoreValidation.Validate(graph, spc.ReportDiagnostic);

            // Stage 3 - resolution: turn each raw declaration into a fully-matched MappingModel,
            // reporting a diagnostic for anything that couldn't be matched along the way.
            var models = graph.GetMappings()
                .Select(declaration => MappingResolver.Resolve(
                    compilation,
                    graph,
                    declaration,
                    spc.ReportDiagnostic))
                .ToImmutableArray();

            // FrozenDictionary only exists on .NET 8+, with no polyfill - ask the consumer's
            // own Compilation whether it resolves rather than guessing from a TFM name.
            var canUseFrozenDictionary =
                compilation.GetTypeByMetadataName("System.Collections.Frozen.FrozenDictionary`2") is not null;

            // #nullable enable and `!` both need C# 8+; netstandard2.0/net5.0 default below
            // that without an explicit <LangVersion>. Same approach: check the actual
            // compilation instead of guessing.
            var languageVersion = compilation.SyntaxTrees
                .OfType<CSharpSyntaxTree>()
                .Select(t => ((CSharpParseOptions)t.Options).LanguageVersion)
                .DefaultIfEmpty(LanguageVersion.CSharp8)
                .Max();
            var useNullableReferenceTypes = languageVersion >= LanguageVersion.CSharp8;

            // Gates interceptor emission below. This is a conservative *proxy*, not the literal
            // mechanism interceptors check - they're actually gated purely by the
            // InterceptorsNamespaces compiler switch, independent of LanguageVersion (confirmed
            // empirically: interception still works with an explicit LangVersion 12 override) -
            // but an old-enough SDK to predate C# 14 rejects/mishandles LangVersion 14 outright, so
            // this stays a safe stand-in for "toolchain new enough" without a separate probe.
            var useCSharp14 = languageVersion >= LanguageVersion.CSharp14;

            // The trimming-annotation attributes shipped with .NET 5/6, not netstandard2.0/older
            // net TFMs. Same ask-the-Compilation approach as canUseFrozenDictionary above.
            var canSuppressTrimWarnings =
                compilation.GetTypeByMetadataName("System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessageAttribute") is not null;

            var capabilities = new ConsumerCapabilities(canUseFrozenDictionary, useNullableReferenceTypes, useCSharp14, canSuppressTrimWarnings);

            // Stage 4 - emission: one generated file for the whole compilation.
            var source = MappingEmitter.Emit(models, capabilities, interceptedCallSites, spc.ReportDiagnostic);
            spc.AddSource("GeneratedMappings.g.cs", source);
        });
    }

    // Cheap syntactic pre-filter, run on every node in the compilation - deliberately no semantic
    // binding here (that happens in TryGetInterceptedMapCall, and only for nodes that pass this).
    // Matches `X.Map<T1,T2>(arg)` / `X.Map<T1,T2>(arg1, arg2)` where X's rightmost identifier is
    // "GeneratedMappings" - covers `GeneratedMappings.Map<,>`, `GeneratedMapper.GeneratedMappings.Map<,>`,
    // and `global::GeneratedMapper.GeneratedMappings.Map<,>`. An unqualified call via
    // `using static GeneratedMapper.GeneratedMappings;` is a known, accepted gap (falls back to the
    // dictionary dispatcher, always correct, just not intercepted) - deliberately not matched, since
    // a bare `Map<,>` identifier would be far more likely to collide with an unrelated method.
    private static bool IsCandidateMapInvocation(SyntaxNode node)
    {
        if (node is not InvocationExpressionSyntax
            {
                Expression: MemberAccessExpressionSyntax
                {
                    Name: GenericNameSyntax { Identifier.ValueText: "Map", TypeArgumentList.Arguments.Count: 2 }
                } memberAccess,
                ArgumentList.Arguments.Count: 1 or 2
            })
        {
            return false;
        }

        return memberAccess.Expression switch
        {
            IdentifierNameSyntax { Identifier.ValueText: "GeneratedMappings" } => true,
            MemberAccessExpressionSyntax { Name.Identifier.ValueText: "GeneratedMappings" } => true,
            _ => false
        };
    }

    // Resolves only the two type-argument syntax nodes semantically - never the `Map` method
    // symbol itself, which can't resolve here (see this method's caller for why). Returns null for
    // anything that can't become a real interceptor: an unresolved type argument, an open generic
    // type parameter (the call site isn't a closed instantiation), or a location the compiler can't
    // produce an interceptable token for.
    private static InterceptedMapCall? TryGetInterceptedMapCall(GeneratorSyntaxContext ctx, System.Threading.CancellationToken ct)
    {
        var invocation = (InvocationExpressionSyntax)ctx.Node;
        var memberAccess = (MemberAccessExpressionSyntax)invocation.Expression;
        var generic = (GenericNameSyntax)memberAccess.Name;
        var typeArguments = generic.TypeArgumentList.Arguments;

        var sourceType = ctx.SemanticModel.GetTypeInfo(typeArguments[0], ct).Type;
        var destinationType = ctx.SemanticModel.GetTypeInfo(typeArguments[1], ct).Type;
        if (sourceType is null or IErrorTypeSymbol || destinationType is null or IErrorTypeSymbol)
            return null;
        if (sourceType.TypeKind == TypeKind.TypeParameter || destinationType.TypeKind == TypeKind.TypeParameter)
            return null;

        // Defensive, not just assumed safe: this exact API's null/throw behavior for an
        // uninterceptable location wasn't independently verified for every edge case, only for the
        // plain top-level static calls this predicate actually matches.
        InterceptableLocation? location;
        try
        {
            location = ctx.SemanticModel.GetInterceptableLocation(invocation, ct);
        }
        catch (InvalidOperationException)
        {
            location = null;
        }

        if (location is null)
            return null;

        return new InterceptedMapCall(
            sourceType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            destinationType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            invocation.ArgumentList.Arguments.Count == 2,
            location.Version,
            location.Data);
    }
}
