using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace GeneratedMapper.Generator;

// Turns the resolved MappingModel list into GeneratedMappings.g.cs. Split by responsibility:
//   - MappingEmitter.Imperative.cs  - the To{Dest}() extension methods.
//   - MappingEmitter.Projection.cs  - the ProjectTo{Dest}() IQueryable extension methods.
//   - MappingEmitter.Dispatcher.cs  - the runtime dispatcher and IMapper service.
// GM006 (below) is the one whole-mapping rejection, checked here since it needs three fields
// together (DestinationIsInitOnly, DestinationHasParameterlessConstructor,
// ConstructorParameterProperties).
internal static partial class MappingEmitter
{
    public static string Emit(
        IReadOnlyCollection<MappingModel> mappings,
        bool useFrozenDictionary,
        bool useNullableReferenceTypes,
        Action<Diagnostic>? report = null)
    {
        var validMappings = new List<MappingModel>();

        foreach (var mapping in mappings)
        {
            // Init-only property + no parameterless constructor + no matched constructor
            // (see MappingResolver.TryMatchConstructor) can't be built at all - skipped rather
            // than emitting code that won't compile.
            if (HasInitOnlyProperty(mapping) &&
                !mapping.DestinationHasParameterlessConstructor &&
                mapping.ConstructorParameterProperties is null)
            {
                report?.Invoke(Diagnostic.Create(
                    Diagnostics.NoParameterlessConstructor,
                    Location.None,
                    mapping.Source.DisplayName,
                    mapping.Destination.DisplayName));
                continue;
            }

            validMappings.Add(mapping);
        }

        // Keyed lookup for MappingEmitter.Projection.cs to inline a nested/element type's own
        // projection expression instead of calling a method (SQL projections can't call methods).
        var byPair = validMappings.ToDictionary(m => (m.Source.FullyQualifiedName, m.Destination.FullyQualifiedName));

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        if (useNullableReferenceTypes)
            sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        if (useFrozenDictionary)
            sb.AppendLine("using System.Collections.Frozen;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Linq.Expressions;");
        sb.AppendLine();
        // File-scoped namespace (`namespace X;`) needs C# 10 - always emit the braced form.
        sb.AppendLine("namespace GeneratedMapper");
        sb.AppendLine("{");
        sb.AppendLine("public static class GeneratedMappings");
        sb.AppendLine("{");

        foreach (var mapping in validMappings)
            EmitMapping(sb, mapping, useNullableReferenceTypes, report);

        foreach (var mapping in validMappings)
            EmitProjection(sb, mapping, byPair, report);

        EmitGenericDispatcher(sb, validMappings, useFrozenDictionary);

        sb.AppendLine("}");
        sb.AppendLine();

        EmitMapperService(sb, validMappings);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static bool HasInitOnlyProperty(MappingModel mapping)
        => mapping.Properties.Any(p => p.DestinationIsInitOnly);

    private static string MaterializeCall(CollectionShape shape)
        => shape switch
        {
            CollectionShape.Array => "ToArray()",
            CollectionShape.HashSet => "ToHashSet()",
            _ => "ToList()"
        };
}
